name: Docker

on:
  push:
    branches: [main]
    tags: ['v*']

jobs:
  publish:
    uses: sampaiobrenner/fcg-orchestration/.github/workflows/docker-publish.yml@main
    with:
      image-name: fcg-users-api
    permissions:
      contents: read
      packages: write
